### DISCUSSION TITLE
Tutorial: Converting an existing project to a Calkit project

### DISCUSSION THREAD

**Discussion by petebachant** [calkit/calkit#241] [General]
This is a discussion thread for the tutorial [Converting an existing project to a Calkit project](https://docs.calkit.org/tutorials/existing-project/).

Questions or comments?

**Comment by rebeccamccabe** [comment]
What steps should be taken if my existing project already uses source control and already has a (very large) overleaf for the publication? 
It is a matlab project https://github.com/symbiotic-engineering/MDOcean, and I currently use CI with github actions and matlab unit test framework to run my optimization and validation study and generate all the figures reproducibly. I also auto-generate some latex tables from the results, but don't have automatic latex integration set up, I copy paste the auto-generated latex code, and manually upload the auto-generated figure pdfs, into my overleaf document.

**Reply by petebachant** [reply]
The first thing you'll want to do is download your files from Overleaf and add them to the MDOcean repo. You can do that by clicking on the "menu" button in the upper left corner on Overleaf, downloading the source, and unzipping into the repo. From the README, it sounds like you have a conference paper as well, so maybe you want to have a `pubs` directory, and put both as subdirectories inside that.

Then you will want to `git add` and `git commit` only the text files from the Overleaf folder, not the figures or PDF, since you'll generate those with the pipeline.

Next, you can turn the project into a Calkit project with (requires Calkit v0.21.5; update with `pip install --upgrade calkit-python`):

```sh
calkit new project . \
    --title MDOcean \
    --name mdocean \
    --description "Multidisciplinary Design Optimization (MDO) to optimize an ocean wave energy converter (WEC)." \
    --cloud \
    --public
```

To use the `--cloud` option, you'll need to ensure you've [set your Calkit token](https://docs.calkit.org/cloud-integration/).

Then it's time to start building the pipeline. You probably want to have one stage per figure (and table), and then of course one to build the paper, which we can do with a Docker environment, created with:

```sh
calkit new docker-env --name tex --image texlive/texlive:latest-full
```

In `dvc.yaml`, start adding stages like:

```yaml
# In dvc.yaml
stages:
  # A stage to make a figure
  plot-something:
    cmd: matlab -noFigureWindows -batch "run('scripts/plot_something.m');"
    deps:
      - scripts/plot_something.m
      - data/raw. # TODO: Are there data file dependencies?
    outs:
      - figures/something.png
    meta:
      calkit:
        type: figure
        title: Something
        description: A plot of something.
  # A stage to make a table
  make-results-table:
    cmd: matlab -noFigureWindows -batch "run('scripts/make_table.m');"
    deps:
      - scripts/make_table.m
      # TODO: Add more dependencies if they exist
    outs:
      - tables/my-table.tex:
          cache: false # No need to cache with DVC since this is a small text file
  # A stage to build the paper
  build-paper:
    cmd: >
      calkit xenv -n tex --
      latexmk -cd -interaction=nonstopmode -pdf pubs/article/paper.tex
    deps:
      # Set the figures and tables directories as dependencies so we rebuild on change
      - figures
      - tables
      - pubs/article/paper.tex
    outs:
      - pubs/article/paper.pdf
    meta:
      calkit:
        type: publication
        kind: journal-article
        title: This is the title of my article
        description: This is the description of my article.
```

To include your LaTeX tables in the manuscript so you don't need to copy/paste them, you can write the tables out to their own `.tex` files, e.g., in a `tables` subdirectory, and use the `\input` command in the manuscript like:

```tex
\begin{table}[htbp]
  \centering
  \caption{Summary of Experimental Results}
  \label{tab:experimental_results}
  % Use table data from ../../tables/my-table.tex
  \input(../../tables/my-table)
\end{table}
```

If you want to add a dev container spec to the project (helpful if you or one of your collaborators wants to edit in GitHub Codespaces), you can do so with:

```sh
calkit update devcontainer
```

However, I have not yet set up MATLAB in a dev container, but it looks like it's possible to [add as a feature](https://github.com/mathworks/devcontainer-features/tree/main/src/matlab).

Finally, you can setup a GitHub Actions workflow to execute `calkit run` and `calkit save` to build and push all of your artifacts to the cloud. There's an example [here](https://github.com/calkit/example-basic/blob/main/.github/workflows/run.yml), though you'll need to add the `setup-matlab` step. You'll also need to ensure you set a `CALKIT_DVC_TOKEN` secret in GitHub Actions.

This should get you into a fully-reproducible state, and if you split up your MATLAB scripts well, you will be able to skip steps in the pipeline whose cached outputs are still valid, saving computation time.

Definitely let me know if anything goes wrong with any of these!
