### ISSUE TITLE
I want to be able to declare system-level dependencies

### ISSUE THREAD

**Issue by petebachant** [calkit/calkit#121]
These should then be checked for existence as the start of `calkit run`, so we know if we should even try to run the pipeline.

Should we be able to make them system-dependent? Related to #64 

For example, what if I'm running a certain stage on an HPC environment? I don't want to need to install all the other system-level dependencies other stages might depend on, do I?

In `calkit.yaml`:

```yaml
dependencies:
  - calkit>=0.8.5
  - conda
  - pixi
  - docker
  - openfoam:
      only_on_hostname: some-computer
      notes: This must be installed system-wide for some reason instead of using a Docker image
```

Could also use `uuid.UUID(int=uuid.getnode())` to identify a machine.
