### ISSUE TITLE
I want to be able to declare/store secrets or other environmental variables necessary to run a project

### ISSUE THREAD

**Issue by petebachant** [calkit/calkit#122]
Example: Imagine we wanted to reproduce [this project](https://github.com/eantonini/climapower). We would need a CDS API key to do so. Can we make it so the user needs to obtain one and set it in a secure way before running the pipeline?

```sh
calkit new secret CDS_API_KEY my-secret-value-here
```

Then maybe we can always inject those when running the pipeline or define them for certain environments

```yaml
environments:
  main:
    kind: conda
    path: envs/main.yml
    env:
      - secret: CDS_API_KEY
secrets:
  CDS_API_KEY: # TODO: How to store this properly?
```

Should we allow global secrets? It might be smarter to isolate them to each project. We could also do something like allowing them to be pulled from the cloud, or perhaps sync a `.env` file.

We could also consider a more general definition for system-level dependencies, which includes software, files, and environmental variables:

```yaml
dependencies:
  - docker>=1.2
  - kind: app
    name: git
    version: ">=2.1"
  - kind: env-var
    name: AWS_ACCESS_KEY_ID
    alternatives: # Some file? How to notate this?
  - kind: file
    path: ~/.aws/credentials
    description: AWS credentials
```

## Environmental variable handling

```sh
calkit config set-env-var SOME_VARIABLE=sup-lol
```

```sh
calkit config set-env-var --global SOME_VARIABLE=sup-lol
```

We can have `.env` files in projects and in `~/.calkit/.env`. And we need to make sure we add these to `.gitignore`. These files file be sourced in `calkit run` and `calkit xenv`. When setting at the project level, we should probably add this to the project dependencies, or make an option to do so.

In the future we could possibly allow for `.env` syncing.
