### ISSUE TITLE
I want it to be easy to create a LaTeX diff PDF between multiple versions of a publication

### ISSUE THREAD

**Issue by petebachant** [calkit/calkit#139]
We could create a pipeline stage to build these, then add different versions to the publication metadata?

```yaml
publications:
  - path: paper.pdf
    versions:
      - path: archive/paper-v1.pdf
        diff_path: archive/diffs/paper-main-vs-v1.pdf
        git_tag: # The tag where this was paper.pdf?
        description: The last round of reviews
```

or we could simply not store them in the repo and rely on the DVC cache for these? That's a bit more complex.

This could also be a use case for a snapshotting feature, though we'd need a snapshot of all inputs to create the diff.

It could also be something like `ck new latexdiff-stage paper/main.pdf v2 v1`, which can use the same environment as the main doc, but each time it needs to be rebuilt, we use a temporary directory.

https://claude.ai/chat/b2e8a052-4d89-4697-b088-e0cf5d6cd23d
