### ISSUE TITLE
I can define an HPC cluster or other remote (SSH) environment in which to run all or part of my pipeline

### ISSUE THREAD

**Issue by petebachant** [calkit/calkit#14]
What would the path be, an SSH host or something? What would the command be in the workflow file?

Path could be to an SSH env description in `.calkit/envs` or go directly into the env description

## SSH environment config file

```yaml
host: 127.0.0.1
port: 22
user: pete
key: ~/.ssh/my-key
project_dir: ~/my-cluster-folder
```

## Direct definition

```yaml
environments:
  the-cluster:
    kind: ssh
    host: 127.0.0.1
    user: pete
    key: ~/.ssh/my-key
    sync_paths:
      - data
      - scripts
```

## What happens when we run a command in the remote environment?

1. We should probably sync files back and forth. Maybe this belongs in the environment definition itself. Should we use Git or DVC for this, or just `scp`?
2. Should we have Calkit installed there? We probably assume that the environment is managed by some other entity and our local Calkit instance is not responsible for managing environments there.
