### ISSUE TITLE
I want to use a notebook as a pipeline stage for a figure

### ISSUE THREAD

**Issue by petebachant** [calkit/calkit#16]
```
calkit add figure --pipeline notebook.ipynb --notebook-cell 5
```

Can we then rerun the notebook and extract the figure, uploading it to DVC?

See https://github.com/Octoframes/jupyter_capture_output

Maybe we could alternatively do something like this with the calkit CLI:

```yaml
  # This stage runs a (temp) notebook and extracts a figure from it
  plot-bl-profile:
    cmd: |
      calkit notebook-output
      --cell-tag bl-profile
      -o figures/bl-profile.png
      notebook.ipynb
    deps:
      - notebook.ipynb
    outs:
      - figures/bl-profile.png
```

Could even use comments or a magic to tag the cell we want as output. If you use the magic in a cell and run it, it adds both to the `calkit.yaml` and `dvc.yaml` files? The stage gets the notebook as an input so we always know if we need to rerun it?

```python
%%calkit figure --stage-name make-my-figure -o figures/my-figure.png
```

This concept could also be used as a decorator on a function. I believe someone else made a package like that.

```python
@calkit.dataset(output="results/some-data.parquet", deps="data/raw", title="Some results")
def calc_my_thing() -> pd.DataFrame:
    return pd.DataFrame(range(5))
```

We should also learn how to make these partitioned so `dvc repro` isn't hugely expensive if only a subset of `data/raw` was changed. `calkit run myapp.py` will then update `dvc.yaml` and `calkit.yaml`, then run `dvc repro`.
