### ISSUE TITLE
I want others to be able to see interactive/dynamic visualizations of my results, like calculations

### ISSUE THREAD

**Issue by petebachant** [calkit/calkit#167]
It would be nice if these could easily be viewed up on calkit.io, which means they'd need to be static HTML or some sort of very limited logic computed on the back end.

Maybe we could have a dynamic figure type like:

```yaml
inputs:
  - name: angle_of_attack
    min: 0
    max: 20
    step: 1
    default: 0
    ui: slider-vertical
figures:
  - path: figures/naca0012-clcd.json
    stage: plot-clcd
    add_hlines:
      - linestyle: dashed
        color: black
        x: "{angle_of_attack}"
  - path: figures/naca0012-umag-{angle_of_attack}-umag.png
    stage: "plot-flow@{angle_of_attack}"
```

which is simply looking up other figures and combining them based on the input value.
