### ISSUE TITLE
I want it to be even easier than DVC to define a pipeline

### ISSUE THREAD

**Issue by petebachant** [calkit/calkit#218]
Imagine something like this in `calkit.yaml`:

```yaml
pipeline:
  get-data:
    kind: python-script # Implied from environment and script?
    script: scripts/get-data.py
    environment: main
  plot-weekly-dists:
    kind: python-script
    script: scripts/plot-weekly-dists.py
    environment: main
  plot-weekly-energy:
    kind: python-script
    script: scripts/plot-weekly-energy.py
    environment: main
  build-paper:
    kind: latex
    environment: tex
    target: paper/paper.tex
    deps_from_stage_outs: 
      - plot-weekly-energy
```

We could use an LLM or other analysis to detect inputs and outputs, compile to `dvc.yaml`, then run.

If the pipeline is defined in `calkit.yaml`, we should note in `dvc.yaml` that it was auto-generated, and overwrite when executing `calkit run`.

We could also do things like add `input_from_stage_outs` keys.

Should we have a `stages` subobject so we can define things about the pipeline, e.g., its type? We should make these stages supersets of DVC stage objects, so they can be written very similarly.

Can we auto-detect outputs? Can we auto-detect deps?
