### ISSUE TITLE
I want to declare instructions or protocols for how to perform certain tasks or procedures so I can easily execute them

### ISSUE THREAD

**Issue by petebachant** [calkit/calkit#27]
We could potentially use the CLI for this. Ideas:

```sh
calkit procedures exec daily-routine
```

or

```sh
calkit run --procedure daily-routine
```

```yaml
procedures:
  daily-routine:
    description: |
      The procedure to be run daily.
    imported_from:
    steps:
      - Open the app
      - Click the button
      - Clean up the lab
      - Back up all the data with calkit add and calkit push
```

Other commands:
- `calkit procedures list` or `calkit list procedures`
- `calkit new procedure`?

When running a procedure, we will prompt the user for each step. Once each step is completed, the user presses enter, and there is a row logged somewhere in the repo. Should they be able to enter something as output? 

The output can be logged in `.calkit/procedures/runs/{name}/{start_ts}.yaml` or maybe to CSV, like

| procedure_name | event_type | event_detail | timestamp | user_email | user_input |
|------------------|-------------|------------|------|-----|-----|
| daily-routine       | started-procedure |     |   2024-01-01 00:00:01 | petebachant@gmail.com  |    | 
| daily-routine     | completed-step | Open the app |  2024-01-02 00:00:10 |  petebachant@gmail.com  |   |

## Other notes and questions

- We should not allow running a procedure with a dirty `calkit.yaml` file. We may want to log the git version in the event log as well.
- Should we have a more complex model for a step? You could imagine a step having multiple named user inputs to aid in running a procedure. You could imagine running a command to bring up an app to use.
