### ISSUE TITLE
I want it to be easy to add a notebook clean/execute stage to my pipeline, or I want it to be easy to use notebooks reproducibly

### ISSUE THREAD

**Issue by petebachant** [calkit/calkit#327]
```sh
calkit new notebook-exec-stage
```

or

```sh
calkit nb create-stage
```

The goal is to simplify creating something like this, that runs a notebook and produces some static output:

```yaml
  strip-notebook-outputs:
    cmd: conda run -n bl-turb-mod calkit nb clean notebook.ipynb
    deps:
      - notebook.ipynb
    outs:
      - .calkit/notebooks/cleaned/notebook.ipynb:
          cache: false
  run-notebook:
    cmd: conda run -n bl-turb-mod calkit nb execute --to=html notebook.ipynb
    deps:
      - .calkit/notebooks/cleaned/notebook.ipynb
      - sim/cases/k-epsilon-ny-15/postProcessing
      - sim/cases/k-epsilon-ny-20/postProcessing
      - sim/cases/k-epsilon-ny-30/postProcessing
      - sim/cases/k-epsilon-ny-40/postProcessing
      - sim/cases/k-epsilon-ny-60/postProcessing
      - sim/cases/laminar-ny-40/postProcessing
    outs:
      - .calkit/notebooks/html/notebook.html
```

Those commands of course need to be inverted. Calkit runs the nbconvert commands in the Conda environment instead of Calkit being run in the Conda environment.

Can we condense this into a single stage? This could be a higher-level stage type in the Calkit pipeline, which compiles to a DVC pipeline (#262).

Maybe this also needs to add to the project notebooks.

## As a Calkit pipeline stage

```yaml
pipeline:
  my-notebook:
    kind: jupyter-notebook
    notebook_path: my-notebook.ipynb
    environment: my-notebook-env
    save_html: true
    outputs:
      - figures/whatever
```

`calkit status` should then show the user when a notebook is out of data.

## Breaking a notebook down into multiple DVC stages

Can we do this? Can we turn a notebook into a pipeline and cache what we need to cache so notebooks can be rerun quickly? Can we allow users to do ad hoc exploration in the notebook, get to a point where they're happy with how it's running, then run the entire project to check the "final" result?
