### ISSUE TITLE
I want to be able to declare my MATLAB environment

### ISSUE THREAD

**Issue by petebachant** [calkit/calkit#331]
Version, toolboxes, path settings (bad)?

The description can be exported with `matlab -batch ver`, and looks something like:

```
WARNING: package sun.awt.X11 not in java.desktop
WARNING: package sun.awt.X11 not in java.desktop
------------------------------------------------------------------------------
MATLAB Version: 24.2.0.2863752 (R2024b) Update 5
MATLAB License Number: 865865
Operating System: macOS  Version: 15.4.1 Build: 24E263 
Java Version: Java 11.0.27+0 with Homebrew OpenJDK 64-Bit Server VM mixed mode
------------------------------------------------------------------------------
MATLAB                                                Version 24.2        (R2024b)
Simulink                                              Version 24.2        (R2024b)
Global Optimization Toolbox                           Version 24.2        (R2024b)
MATLAB Report Generator                               Version 24.2        (R2024b)
Optimization Toolbox                                  Version 24.2        (R2024b)
Parallel Computing Toolbox                            Version 24.2        (R2024b)
Simscape                                              Version 24.2        (R2024b)
Simscape Multibody                                    Version 24.2        (R2024b)
Statistics and Machine Learning Toolbox               Version 24.2        (R2024b)
Symbolic Math Toolbox                                 Version 24.2        (R2024b)
```

**Comment by rebeccamccabe** [comment]
I use `[fList,pList] = matlab.codetools.requiredFilesAndProducts('my_script.m')` to get only the packages used in my project, since I use the same matlab environment for many different projects. This assumes the toolboxes are already installed. Then I manually add them to my list of packages in the setup-matlab github action, because the package naming syntax is frustratingly slightly different between the requiredFilesAndProducts function and [mpm](https://github.com/mathworks-ref-arch/matlab-dockerfile/tree/main/mpm-input-files).

**Comment by petebachant** [comment]
Interesting. I hadn't seen mpm yet. I wonder if the most reproducible approach would be to automate the creation of a Docker image, since MATLAB doesn't have the concept of a virtual environment. I'm sure the GitHub Action does something similar under the hood anyway. How are you ensuring GitHub Actions has access to your license?

**Comment by rebeccamccabe** [comment]
For public repos you don’t actually need a matlab license (which is
surprising). For private repos I think you can configure it somehow in the
CI yaml, I haven’t done that yet.

-Becca

**Comment by petebachant** [comment]
I have a working design going in https://github.com/calkit/calkit/pull/262. Basically you simply declare the version and products, and Calkit will build you a Docker image as needed to run pipeline stages in a container. For example:

```yaml
environments:
  my-matlab:
    kind: matlab
    version: R2024b
    products:
      - Statistics_and_Machine_Learning_Toolbox
      - Parallel_Computing_Toolbox
pipeline:
  stages:
    collect-data:
      kind: matlab-script
      environment: my-matlab
      script_path: scripts/collect_data.m
      outputs:
        - data/raw/data.parquet
```
