### ISSUE TITLE
I want to be able to define multiple uv project environments in my project

### ISSUE THREAD

**Issue by petebachant** [calkit/calkit#361]
This is possible with the `uv run --project` command, with a structure like:

```
env1/
    pyproject.toml
env2/
    pyproject.toml
```

```yaml
# In calkit.yaml
environments:
  env1:
    kind: uv
    path: env1/pyproject.toml
  env2:
    kind: uv
    path: env2/pyproject.toml
```

```sh
uv run --project env1 which python
```

Each environment will become its own virtual environment, and can be used independently. Commands still run from wherever `uv` was called as well.

Default path can be `.calkit/envs/{name}/pyproject.toml`, which can contain:

```toml
[project]
name = "jlab-demo-uv1"
version = "0.1.0"
description = "A demo JupyterLab project using CalKit with uv1 environment"
readme = "README.md"
requires-python = "==3.14.*"
dependencies = [
    "marimo",
    "polars",
    "pandas",
    "numpy",
    "scipy",
    "seaborn",
    "statsmodels",
    "pyzmq>=27.1.0",
]
```
