### ISSUE TITLE
I want to use Google Colab as an environment for a notebook or as the main place to work on my project

### ISSUE THREAD

**Issue by petebachant** [calkit/calkit#377]
There is a CLI...

Would also open up using Google Drive as a DVC remote potentially.

Or for those who like the Colab interface, we want to automatically sync to a repo on GitHub and DVC remote.

Maybe a cell like

```sh
!calkit colab connect
```

at the top could prompt the user to log in to calkit.io, which would give us Git and DVC access. Storage management is a little wonky with Colab though.

An alternative could be to host a GPU-enabled JupyterHub on calkit.io and have a user's environment set up and ready when they launch.

[ux prototyping](https://colab.research.google.com/drive/1D7yhTAhoBcv2M6cRddmfPYrXZBC56DDC#scrollTo=29ZZkTGS6fof)

Stage design:

```yaml
colab-notebook-1:
  kind: jupyter-notebook
  environment: colab:main
  notebook_path: notebooks/main.ipynb
  colab_url: https://colab.research.google.com/drive/1D7yhTAhoBcv2M6cRddmfPYrXZBC56DDC
  inputs: []
  outputs: []
```
