### ISSUE TITLE
I want to be able to create and view a plan where I run a similar process multiple times with different parameters

### ISSUE THREAD

**Issue by petebachant** [calkit/calkit#38]
DVC has a way to do this, but it may be a bit low level to go in and edit directly. Can we "compile" a higher level plan into a `dvc.yaml` stage? Can we have different sections? Can we add to them on the fly to ensure our a hoc explorations are tracked? See the [DVC docs on "foreach" stages](https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#foreach-stages).

## Concrete example

I want to run a mesh independence study. We can parameterize this with a single metric, `nx`, the number of cells in the x direction. The number of cells in the y-direction will always be proportional. For each of these runs I want to extract a mean velocity profile to look at convergence. What if I want to add another parameter, like which turbulence model is used? I guess this becomes a matrix. Can we do the mesh independence with one turbulence model and extrapolate it out, or should we do it with all?

Did this in the BL turbulence model project with this stage:

```yaml
  mesh-independence:
    matrix:
      ny: [15, 20, 30, 40, 60]
      turbulence: [k-epsilon]
    cmd: >
      cd sim && bash run-docker.sh
      python run.py --ny ${item.ny} -f --turbulence-model ${item.turbulence}
    deps:
      - sim/system/blockMeshDict.template
      - sim/run.py
      - sim/system/sample
    outs:
      - sim/cases/${item.turbulence}-ny-${item.ny}/postProcessing
```

## Possible design

```sh
calkit new foreach-stage \
    --cmd "calkit run-env python run.py --turbulence {var}" \
    --name run-sim \
    --dep system \
    --dep constant/transportProperties \
    --dep run.py \
    --dep Dockerfile \
    --out "cases/{var}/postProcessing" \
    "laminar" "k-epsilon" "k-omega"
```

```sh
calkit list foreach-stages
```

can then parse through `dvc.yaml` and only print these, perhaps in a nice table format.

We could potentially do something similar for matrix stages.
