### ISSUE TITLE
I want to be able to work on reviews for articles, but to keep them private

### ISSUE THREAD

**Issue by petebachant** [calkit/calkit#45]
Usually reviews need to be private, though the responses to them could be public. There is some pain around managing the response "to-do list". Some possible solutions:

1. Use the Calkit cloud system to do this. Reviews and responses can go in a database table and be managed on the website.
2. Use a private GitHub repo for the reviews alone. Each review could become a GitHub issue, or perhaps each comment in a review could become its own issue. This paper review repo could be part of `calkit.yaml`, like

```yaml
publications:
  - path: paper.pdf
    kind: journal-article
    review_repo_url: https://github.com/myname/my-paper-reviews
```
