### ISSUE TITLE
I want some way to be able to define and track things to run on a schedule like cron jobs

### ISSUE THREAD

**Issue by petebachant** [calkit/calkit#47]

**Comment by petebachant** [comment]
We could also have that as a kind of input:

```yaml
pipeline:
  stages:
    run-daily:
      inputs:
        - kind: current-day
          timezone: utc
```

So stages will run once for the current day, then not again.
