### ISSUE TITLE
I want it to be easier to create a Docker image

### ISSUE THREAD

**Issue by petebachant** [calkit/calkit#56]
Learning how to create a Dockerfile is pretty advanced for a new researcher. Can we make this super easy? Maybe we can have some canned recipes to build Dockerfiles automatically depending on what dependencies they need.

In `dvc.yaml`, we could have:

```yaml
stages:
  make-docker:
    cmd: >
      calkit make docker 
      --base microfluidica/openfoam:2406
      --add-mamba
      -o ./Dockerfile 
      --conda-env ./environment.yml
      --build
      --create-run-script
    deps:
      - environment.yml
    outs:
      - Dockerfile:
          cache: false
      - run-docker.sh: # A script to easily mount the local directory and run whatever inside the container
          cache: false
    meta:
      calkit:
        type: environment
        name: my-environment
        kind: docker
```

The design above is almost at complex as writing the Dockerfile from scratch though. There is some abstraction there, but it wouldn't cover the use case where we want to build a new OpenFOAM library, for example.
