### ISSUE TITLE
I want to be able to declare dependencies that are only necessary for certain pipeline stages

### ISSUE THREAD

**Issue by petebachant** [calkit/calkit#64]
Imagine I have two different computers being used for a project, and I only need a certain piece of software on one of them.

In `calkit.yaml`:

```yaml
dependencies:
  - name: docker
    stage: check-docker-installed
    path: docker-version.txt
```

In `dvc.yaml`:

```yaml
stages:
  check-docker-installed:
    cmd: >
      calkit check-call "docker --version > docker-version.txt" 
      --only-hostname some-computer 
      --message "Ensure Docker is installed"
    meta:
      calkit:
        type: dependency
        name: docker
        path: docker-version.txt
```
