### ISSUE TITLE
I want to be able to collect data from NI devices with a declarative configuration

### ISSUE THREAD

**Issue by petebachant** [calkit/calkit#90]
Imagine being able to define how to collect data in YAML (what device, signal names, sample rate, etc.), then run something like `calkit collect` that will collect data and add it to a dataset, optionally auto-committing and pushing. Could this be part of the pipeline? How would we manage dependencies and cache invalidation? Perhaps we could have a plan for what data to collect.

```yaml
stages:
  collect-data:
    cmd: calkit collect
```

```
equipment:
  daq-devices:
    daq-1:
      mfg: National Instruments
      model: USB-6001
daq-configs:
  config-1:
    device: daq-1
    strategy: continuous
    sample_rate: 1000
    channels:
      force1:
        ...
```

**Comment by petebachant** [comment]
Maybe this should be more like:

```yaml
operators:
  machine-1:
    mode: cron # How does the operator interact with the cloud?
    ops: # What operations should it run and when
      run-pipeline-on-demand:
        kind: run-pipeline
        when: on-demand
      collect-data: # Can this send to cloud and auto-append to dataset, or maybe just git commit on a branch and push
        kind: python-script
        when: continuous
        environment:
          kind: uv
          path: envs/machine-1-py/pyproject.toml
```

Then on the operator machine, we install Calkit and run something like:

```sh
calkit operator install --project petebachant/my-project-1 --name machine-1
```

Will require an operator token to be set.

This would then potentially allow a user to run the pipeline on their local machine (or any machine) from calkit.io.

How to manage a fleet of IoT devices running certain ops, how to rollout changes to them? I suppose the operator controller could periodically make requests out to the cloud to get the latest information about the repo, environment, code version, and update/restart if/when necessary. This way, a merge to `main` can essentially serve as a deployment.

Calkit operators

One per machine typically 

One process or app per operator 

Can do whatever you want but needs an environment? Python script, docker command

Continuous or cron job

Pipeline runner or dataset uploader 

Controller could be posting rows to a status dataset 

GitHub actions can be an operator?

Useful for coffee machine project? Operator on raspberry pi

Running jobs on hpc
