### ISSUE TITLE
I want my conda environment to automatically update if my machine's version is out-of-sync with the file in the repo

### ISSUE THREAD

**Issue by petebachant** [calkit/calkit#99]
I want to be able to run the pipeline with `calkit run`, and if any steps are executed with a `conda` env, that will kick off a rebuild of the environment if it's different or doesn't exist. However, I want this to remain fast if the environment is still up-to-date.

## Concepts

1. Use [conda-lock](https://github.com/conda/conda-lock)
2. Keep a local cache of env check results, keyed by the hash of the local directory. Probably too expensive.
    i. Use the last modified time of the directory as a cache key

We can cache results in `~/.calkit/conda-env-checks/{name}.yml`. We can save data like

```yaml
last_checked: {ts}
last_mtime: {}
prefix:
env_file:
env_file_md5:
last_check_passed: false
last_action:  # rebuilt or null
```

### Algorithm

1. Check the output of `conda env list` to see if the environment even exists. If not, create it.
2. If the environment exists, check our check results cache to see when we last checked, and compare the `mtime` of the directory. If different, we need to run `conda env export` and compare against the env spec file. If it fails the check, we need to rebuild the environment.
3. Output `environment-lock.yml` as the full environment that exists now, without prefix and build information.

## Interface

In `dvc.yaml`, we can have our first stage be something like

```yaml
stages:
  check-conda-env:
    cmd: calkit check-conda-env -f environment.yml -o environment-lock.yml
    outs:
      - environment-lock.yml:
          cache: false
    deps:
      - environment.yml
    always_changed: true
```
